version: 2
workflows:
  version: 2
  build:
    jobs:
    - build
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-dev
      - save_cache:
          paths:
            - ./venv

          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          context: org-global
          command: |
            . venv/bin/activate
            env
            pytest tests
      - run:
          name: run hooks
          command: |
            . venv/bin/activate
            make hooks
      - store_artifacts:
          path: test-reports
          destination: test-reports
